name: First CRA project 
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting.
    name: cra-stage
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: check cache
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: install dep
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Lint
        run: yarn lint

      - name: test
      run: yarn test

      - name: Echo the greeting's time
      run: echo 'The time was ${{ steps.hello.outputs.time }}.'